### ISSUE TITLE
ModuleNotFoundError: No module named 'fairseq_cli'

### ISSUE THREAD

**Issue by ZhenLEI96** [DeepLearnXMU/BigVideo-VMT#1]
我按照md文件进行配置环境，运行sh文件时遇到了这个问题
Traceback (most recent call last):
  File "~/miniconda3/envs/VMT/bin/fairseq-train", line 5, in <module>
    from fairseq_cli.train import cli_main
ModuleNotFoundError: No module named 'fairseq_cli'

Name: fairseq
Version: 0.10.2
Summary: Facebook AI Research Sequence-to-Sequence Toolkit
Home-page: https://github.com/pytorch/fairseq
Author: 
Author-email: 
License: 
Location: /miniconda3/envs/VMT/lib/python3.8/site-packages
Editable project location:/Laize/BigVideo-VMT/fairseq_mmt
Requires: cffi, cython, dataclasses, hydra-core, numpy, regex, sacrebleu, torch, tqdm
Required-by:

**Comment by fringe-k** [comment]
cd fairseq_mmt
pip install --editable ./ 
这一步你做了吗
