### ISSUE TITLE
File missing? --video-ids-path $video_ids_path

### ISSUE THREAD

**Issue by andongBlue** [DeepLearnXMU/BigVideo-VMT#3]
您好，我在调试您的代码中发现，  `  --video-ids-path $video_ids_path \` 的文件中好像缺失了这个文件。我们的报错显示如下：

`INFO:fairseq_cli.train:Namespace(activation_dropout=0.0, activation_fn='relu', adam_betas='(0.9, 0.98)', adam_eps=1e-08, adaptive_input=False, adaptive_softmax_cutoff=None, adaptive_softmax_dropout=0, all_gather_list_size=16384, arch='video_fushion_encoder_revise_one_merge_before_pewln', attention_dropout=0.0, batch_size=None, batch_size_valid=None, best_checkpoint_metric='bleu', bf16=False, bpe=None, broadcast_buffers=False, bucket_cap_mb=25, checkpoint_shard_count=1, checkpoint_suffix='', clip_norm=0.0, contrastive_strategy='mean+mlp', contrastive_temperature=0.002, contrastive_weight=1.0, cpu=False, criterion='cross_modal_criterion_with_ctr_revise', cross_self_attention=False, ctr_dropout_rate=0.0, curriculum=0, data='/home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset/fairseq_bins/en2zh_bin', data_buffer_size=10, dataset_impl=None, ddp_backend='c10d', decoder_attention_heads=8, decoder_embed_dim=512, decoder_embed_path=None, decoder_ffn_embed_dim=2048, decoder_input_dim=512, decoder_layerdrop=0, decoder_layers=6, decoder_layers_to_keep=None, decoder_learned_pos=False, decoder_normalize_before=False, decoder_output_dim=512, device_id=0, disable_validation=False, distributed_backend='nccl', distributed_init_method=None, distributed_no_spawn=False, distributed_num_procs=0, distributed_port=-1, distributed_rank=0, distributed_world_size=0, distributed_wrapper='DDP', dropout=0.1, empty_cache_freq=0, enable_cls=0, encoder_attention_heads=8, encoder_embed_dim=512, encoder_embed_path=None, encoder_ffn_embed_dim=2048, encoder_layerdrop=0, encoder_layers=0, encoder_layers_to_keep=None, encoder_learned_pos=False, encoder_normalize_before=False, eval_bleu=True, eval_bleu_args='{"beam": 4,"lenpen":1.0}', eval_bleu_detok='moses', eval_bleu_detok_args=None, eval_bleu_print_samples=False, eval_bleu_remove_bpe='@@ ', eval_tokenized_bleu=False, fast_stat_sync=False, find_unused_parameters=False, finetune_from_model=None, fix_batches_to_gpus=False, fixed_validation_seed=None, fp16=True, fp16_init_scale=128, fp16_no_flatten_grads=False, fp16_scale_tolerance=0.0, fp16_scale_window=None, fushion_encoder_attention_heads=8, fushion_encoder_embed_dim=512, fushion_encoder_embed_path=None, fushion_encoder_ffn_embed_dim=2048, fushion_encoder_layerdrop=0, fushion_encoder_layers=6, fushion_encoder_layers_to_keep=None, fushion_encoder_learned_pos=False, fushion_encoder_normalize_before=False, gen_subset='test', id_type='original', ignore_prefix_size=0, keep_best_checkpoints=10, keep_interval_updates=10, keep_last_epochs=-1, label_smoothing=0.1, layer_wise_attention=False, layernorm_embedding=False, left_pad_source='True', left_pad_target='False', load_alignments=False, localsgd_frequency=3, log_format=None, log_interval=100, lr=[0.0007], lr_scheduler='inverse_sqrt', max_epoch=100, max_source_positions=256, max_target_positions=256, max_tokens=4096, max_tokens_valid=4096, max_update=0, max_vid_len=12, maximize_best_checkpoint_metric=True, memory_efficient_bf16=False, memory_efficient_fp16=False, merge_before=True, min_loss_scale=0.0001, min_lr=1e-09, model_parallel_size=1, no_cross_attention=False, no_epoch_checkpoints=False, no_last_checkpoints=False, no_progress_bar=True, no_save=False, no_save_optimizer_state=False, no_scale_embedding=False, no_seed_provided=False, no_token_positional_embeddings=False, nprocs_per_node=1, num_batch_buckets=0, num_shards=1, num_workers=1, only_load_model=False, optimizer='adam', optimizer_overrides='{}', output_encoder_after=0, patience=10, pe_for_video=True, pipeline_balance=None, pipeline_checkpoint='never', pipeline_chunks=0, pipeline_decoder_balance=None, pipeline_decoder_devices=None, pipeline_devices=None, pipeline_encoder_balance=None, pipeline_encoder_devices=None, pipeline_model_parallel=False, profile=False, quant_noise_pq=0, quant_noise_pq_block_size=8, quant_noise_scalar=0, quantization_config_path=None, report_accuracy=False, required_batch_size_multiple=8, required_seq_len_multiple=1, reset_dataloader=False, reset_lr_scheduler=False, reset_meters=False, reset_optimizer=False, restore_file='checkpoint_last.pt', sampling_frames=0, sampling_strategy='None', save_dir='./experiment_result/tf_archvideo_fushion_encoder_revise_one_merge_before_pewln_criCMCCTRRE_tgtzh_lr7e-4_wu4000_mat4096_acc1_me100_seed1_gpu0_wd0.1_dp0.1_vtypeViT_mvlen12_tsuniform_ctrsmean+mlp_ctra_ctrw1.0_ctrt0.002_patience10/', save_interval=1, save_interval_updates=0, scoring='bleu', seed=1, sentence_avg=False, shard_id=0, share_all_embeddings=False, share_decoder_input_output_embed=False, skip_invalid_size_inputs_valid_test=True, slowmo_algorithm='LocalSGD', slowmo_momentum=None, source_lang='en', stop_time_hours=0, target_lang='zh', task='raw_video_translation_from_np', tensorboard_logdir=None, threshold_loss_scale=None, tokenizer=None, tpu=False, train_sampling_strategy='uniform', train_subset='train', truncate_source=False, update_freq=[1], upsample_primary=1, use_bmuf=False, use_dual_ctr=False, use_old_adam=False, use_v2t_ctr=False, user_dir=None, valid_subset='valid', validate_after_updates=0, validate_interval=1, validate_interval_updates=0, video_dropout=0.0, video_feat_dim=768, video_feat_path='/home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset//video_features/ViT', video_feat_type='ViT', video_ids_path='/home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset/', video_layernorm_embedding=True, video_learned_pos=False, warmup_init_lr=1e-07, warmup_updates=4000, weight_decay=0.1, zero_sharding='none')
INFO:fairseq.tasks.raw_video_translation_from_np:[en] dictionary: 36184 types
INFO:fairseq.tasks.raw_video_translation_from_np:[zh] dictionary: 46768 types
INFO:fairseq.data.data_utils:loaded 22548 examples from: /home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset/fairseq_bins/en2zh_bin/valid.en-zh.en
INFO:fairseq.data.data_utils:loaded 22548 examples from: /home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset/fairseq_bins/en2zh_bin/valid.en-zh.zh
INFO:fairseq.tasks.raw_video_translation_from_np:/home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset/fairseq_bins/en2zh_bin valid en-zh 22548 examples
Traceback (most recent call last):
  File "/home/export/base/ycsc_chenkh/chenkh/online1/support/anaconda3/envs/simt_video/bin/fairseq-train", line 8, in <module>
    sys.exit(cli_main())
  File "/online1/ycsc_chenkh/chenkh/andongchen/SimTranslation_multimodel/BigVideo-VMT/fairseq_mmt/fairseq_cli/train.py", line 354, in cli_main
    distributed_utils.call_main(args, main)
  File "/online1/ycsc_chenkh/chenkh/andongchen/SimTranslation_multimodel/BigVideo-VMT/fairseq_mmt/fairseq/distributed_utils.py", line 301, in call_main
    main(args, **kwargs)
  File "/online1/ycsc_chenkh/chenkh/andongchen/SimTranslation_multimodel/BigVideo-VMT/fairseq_mmt/fairseq_cli/train.py", line 65, in main
    task.load_dataset(valid_sub_split, combine=False, epoch=1)
  File "/online1/ycsc_chenkh/chenkh/andongchen/SimTranslation_multimodel/BigVideo-VMT/fairseq_mmt/fairseq/tasks/raw_video_translation_from_np.py", line 330, in load_dataset
    self.datasets[split] = load_VideoLanguageDatasetFromNp(
  File "/online1/ycsc_chenkh/chenkh/andongchen/SimTranslation_multimodel/BigVideo-VMT/fairseq_mmt/fairseq/tasks/raw_video_translation_from_np.py", line 146, in load_VideoLanguageDatasetFromNp
    video_dataset = VideoDatasetFromNp(args,split)
  File "/online1/ycsc_chenkh/chenkh/andongchen/SimTranslation_multimodel/BigVideo-VMT/fairseq_mmt/fairseq/data/video_dataset_from_np.py", line 69, in __init__
    with open(id_file, encoding='utf-8') as file:
FileNotFoundError: [Errno 2] No such file or directory: '/home/export/base/ycsc_chenkh/chenkh/online1/andongchen/SimTranslation_multimodel/BigVideo-VMT/BigVideo_dataset//valid.id'
`
希望获得您的回复，很荣幸可以调试您开源的代码，希望可以多多交流。

**Comment by fringe-k** [comment]
All id_file are under [BigVideo](https://huggingface.co/datasets/fringek/BigVideo/tree/main)
/
text_data, please check it again.
